[package]
name = "leptos_hot_reload"
version = { workspace = true }
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "Utility types used for dev mode and hot-reloading for the Leptos web framework."
readme = "../README.md"
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "2.0", features = [
  "full",
  "parsing",
  "extra-traits",
  "visit",
  "printing",
] }
<<<<<<< HEAD
quote = "1"
rstml = "0.11.0"
proc-macro2 = { version = "=1.0.94", features = ["span-locations", "nightly"] }
parking_lot = "0.12"
walkdir = "2"
camino = "1.1.3"
indexmap = "2"
=======
quote = "1.0"
rstml = "0.12.0"
proc-macro2 = { version = "1.0", features = ["span-locations", "nightly"] }
parking_lot = "0.12.3"
walkdir = "2.5"
camino = "1.1"
indexmap = "2.6"
>>>>>>> 13110a35e2336cf2067b64064ed56cd1d8c4737f
